### ISSUE TITLE
Is the 5.26 requirement strictly needed?

### ISSUE THREAD

**Issue by taupehat** [ericschernoff/Backblaze-B2V2Client#1]
From a current Centos 7 host:
`requires perl '5.026001'; you have only 5.016003; giving up`
Without using perlbrew or some shade-tree repos this code won't install without modification.

So my question is, can we downgrade the Perl version requirement?

**Comment by ericschernoff** [comment]
I’m sorry that I am just now seeing this.  I would need to test on 5.16 to be sure. A lot has changed since 5.16, and I am not sure about the dependencies. 

I will try to test on CentOS this week and update you.

**Comment by ericschernoff** [comment]
Hello,

I attempted the install on CentOS, and some of the dependencies failed, as they wanted a higher version of Perl.

I know the pain of the older version of Perl on CentOS and RHEL, and I understand you probably are stuck with CentOS.  I am sorry I could not be more of a help with this.

-Eric
