### ISSUE TITLE
new_file_name not respected when file_location is used instead of file_contents

### ISSUE THREAD

**Issue by 357r4bd** [ericschernoff/Backblaze-B2V2Client#2]
```
# new_file_name is respected
my $ret = $client->b2_upload_file(
    'bucket_name'   => $primary_bucket,
    'new_file_name' => q{test/hierarchical/new/file/newname.test},
    'file_contents' => Path::Tiny::path($full_path)->slurp_raw,
);

# new_file_name is not resepected

$ret = $client->b2_upload_file(
    'bucket_name'   => $primary_bucket,
    'file_location' => $full_path,
    'new_file_name' => q{test/hierarchical/new/file/newname.test},
);
```

Fix is easy and PR is on the way.

**Comment by ericschernoff** [comment]
Hello,

Thanks for this pull request!  I have merged it in and will be uploading to CPAN momentarily.

-Eric

**Comment by 357r4bd** [comment]
great, happy to help! when I get around to it I might release my "client" since I ended up doing multiple uploads via fork and minimizing the number of logins - worked for a few million files, but needs to be cleaned up

**Comment by ericschernoff** [comment]
Your client sounds amazing!  I hope to see it soon.  Please let me know if I can be of any help.
