### ISSUE TITLE
you really love Path::Tiny xD - what are the options for generating "file_content" in upload?

### ISSUE THREAD

**Issue by 357r4bd** [ericschernoff/Backblaze-B2V2Client#4]
```
        # i really love Path::Tiny
        path($save_to_location)->spew_raw( $self->{b2_response}{file_contents} );
```

Minor suggestion, can you update your POD to reflect the fact that in the upload method, `file_contents` works best when using `Path::Tiny`'s `slurp_raw` method? I only discovered this when inspecting the source to figure out why I couldn't get it to work. But I was also using `file_content` because of Issue #2.

I tried several things to get the contents in there, including: a scalar having slurped up the file traditionally (`$/ = undef`), passing the file handle from an `open`, etc.

I don't know the idiomatic equivalent to `slurp_raw`, but if it's not obvious maybe just say to use `Path::Tiny::slurp_raw` to generate the contents. If I knew, I'd update the POD myself.

Anyway, great module and thanks for sharing it!

**Comment by ericschernoff** [comment]
I apologize for taking so long to respond.  I really need to find where to set GitHub to alert me for new issues.

I will look at the other issue as well as your pull request right now.

**Comment by ericschernoff** [comment]
Thank you again for these suggestions.  I have added notes to the docs about using Path::Tiny->slurp_raw() with this module.  I also think File::Slurp will work, but I find Path::Tiny to be faster.

I am very glad that this module is useful to you.  If there are any other problems, please let me know at ericschernoff at gmail.

Cheers!
